version: "3.8"
services:
  bio-booking-react:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
    # environment:
    #  - REACT_APP_NAME=bio-booking-react
    # env_file:
    # - ./.env
    