# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Bio-booking CI

on:
  push:
    branches: [ Develop ]
  pull_request:
    branches: [ Develop ]

jobs:
  build:
    runs-on: self-hosted
    env:
      working-directory: ../test

    steps:
    - uses: actions/checkout@v2
    - name: Just testing
      run: pwd
      working-directory: ${{env.working-directory}}
    - uses: actions/checkout@v2
    - name: Just testing2
      run: pwd
