# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Bio-booking CI

on:
  push:
    branches: [ Develop ]
  pull_request:
    branches: [ Develop ]

jobs:
  build:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: /home/DevOps/frontend/bio-booking_react

    steps:
    - uses: actions/checkout@v2
    - name: refresh from Github - standard branch is set to Development
      run: sudo git pull

    - uses: actions/checkout@v2
    - name: timestamp
      run: timestamp=$(date +%Y/%m/%d-%H:%M:%S)

    - uses: actions/checkout@v2
    - name: docker compose with Dockerfile.dev and timestamp  
      run: docker-compose -f docker-compose-dev.yml up -d --build --project-name bio-frontend$timestamp

    - uses: actions/checkout@v2
    - name: clear any unused docker image
      run: docker rmi $(docker images -qa -f 'dangling=true')